services:
 # Client
  - type: web
    name: client
    env: static
    rootDir: client
    buildCommand: npm build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # optional
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: api
    env: docker
    rootDir: api
    plan: free
    envVars:
    - key: API_PORT
      value: 5001
    - key: DATABASE_URL
      fromDatabase:
        name: db
        property: connectionString

databases:
  - name: db
    plan: free